Remove target framework for test proj

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -10,12 +10,11 @@ on:
 jobs:
   build: # Test, pack and publish the Open AI nuget package as a build artifact 
     runs-on: ubuntu-latest
-    environment: livetest
     steps:
       - name: Setup .NET
         uses: actions/setup-dotnet@v1
         with:
-          dotnet-version: 7.x
+          dotnet-version: 8.x
 
       - name: Checkout code
         uses: actions/checkout@v2
@@ -27,13 +26,27 @@ jobs:
 
       - name: Test
         run: dotnet test
-          -c Release --no-build
+          --no-build
+          -c Release
           --filter="TestCategory~GitHub"
+          --logger "trx;LogFileName=test-results-github.trx"
+        env:
+          SECRET_VALUE: ${{ secrets.REPOSITORY_SECRET }}
         working-directory: .dotnet
-    
+
+      - name: Test Report
+        uses: dorny/test-reporter@v1
+        if: success() || failure()    # run this step even if previous step failed
+        with:
+          name: dotnet tests          # Name of the check run which will be created
+          path: '**/*.trx'            # Path to test results
+          reporter: dotnet-trx        # Format of test results
+          working-directory: .dotnet/tests
+
       - name: Pack
         run: dotnet pack
-          -c Release --no-build
+          --no-build
+          -c Release
           -o "${{github.workspace}}/packages"
           ${{ github.ref != 'refs/heads/main' && format('--version-suffix="alpha.{0}"', github.run_number) || '' }}
         working-directory: .dotnet
